### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zencatalyst**
Various fixes:
- typos
- grammar
- spelling
- punctuation
- styling improved.

The content remains untouched.

### CODE REVIEW

**Comment by zencatalyst** [comment]
@d-xo Please review this PR.

**Comment by zencatalyst** [comment]
@ClaasBontus Please take a look and review this PR.

**Comment by zencatalyst** [comment]
@ClaasBontus Please take a look at this.

**Review by ClaasBontus — APPROVED** [review]
relax

**Pull request merged**
